import type { Metadata } from "next";
import { Roboto, Fira_Code } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/ThemeProvider";
import QueryProvider from "@/components/QueryProvider";
import AppBar from "@/components/AppBar";
import MainWorkspace from "@/components/MainWorkspace";
import { OpenCollectionsProvider } from "@/context/OpenCollectionsContext";
import ReactDndProvider from "@/components/dnd/ReactDndProvider";
import CardDragLayer from "@/components/dnd/CardDragLayer";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"]
});

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.variable} ${firaCode.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProvider>
            <ReactDndProvider>
              <OpenCollectionsProvider>
                <div className="min-h-screen bg-background">
                  <AppBar />
                  <main className="w-full mx-auto p-2">
                    <MainWorkspace>{children}</MainWorkspace>
                  </main>
                </div>
              </OpenCollectionsProvider>

              {/* Drag layers */}
              <CardDragLayer />
            </ReactDndProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
