import type { Metadata } from "next";
import { Roboto, Fira_Code } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/Providers";
import AppBar from "@/components/AppBar";
import { getServerSession } from "next-auth";
import { authOptions } from "@/auth";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"]
});

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.variable} ${firaCode.variable} antialiased`}>
        <Providers session={session}>
          <div className="min-h-screen bg-background">
            <AppBar />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
